name: Docker Actions

#on: [push]
on: 
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

       - name: "hello-action"
         uses: ./.github/actions/hello-world

       - name: "meow"
         uses: ./.github/actions/cat-facts
#jobs:
#  action:
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: actions/checkout@v1
      
#      - name: "hello-action"
#        uses: ./.github/actions/hello-world
#        with:
#          firstGreeting: "Learning Lab User"

